---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: beacon-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: beacon-manager-role
subjects:
  - kind: ServiceAccount
    name: beacon-controller-manager
    namespace: beacon-system
