//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is a deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatewayHealthPolicy) DeepCopyInto(out *GatewayHealthPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is a deepcopy function, copying the receiver, creating a new GatewayHealthPolicy.
func (in *GatewayHealthPolicy) DeepCopy() *GatewayHealthPolicy {
	if in == nil {
		return nil
	}
	out := new(GatewayHealthPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is a deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GatewayHealthPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is a deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatewayHealthPolicyList) DeepCopyInto(out *GatewayHealthPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GatewayHealthPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is a deepcopy function, copying the receiver, creating a new GatewayHealthPolicyList.
func (in *GatewayHealthPolicyList) DeepCopy() *GatewayHealthPolicyList {
	if in == nil {
		return nil
	}
	out := new(GatewayHealthPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is a deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GatewayHealthPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is a deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatewayHealthPolicySpec) DeepCopyInto(out *GatewayHealthPolicySpec) {
	*out = *in
	out.WithdrawAfter = in.WithdrawAfter
	out.ReadvertiseAfter = in.ReadvertiseAfter
	out.ResyncInterval = in.ResyncInterval
	out.MetalLB = in.MetalLB
	if in.MinHealthyBackendPercent != nil {
		in, out := &in.MinHealthyBackendPercent, &out.MinHealthyBackendPercent
		*out = new(int32)
		**out = **in
	}
	if in.MinHealthyPodPercent != nil {
		in, out := &in.MinHealthyPodPercent, &out.MinHealthyPodPercent
		*out = new(int32)
		**out = **in
	}
	if in.Exemptions != nil {
		in, out := &in.Exemptions, &out.Exemptions
		*out = make([]GatewayReference, len(*in))
		copy(*out, *in)
	}
	if in.GatewayClassNames != nil {
		in, out := &in.GatewayClassNames, &out.GatewayClassNames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is a deepcopy function, copying the receiver, creating a new GatewayHealthPolicySpec.
func (in *GatewayHealthPolicySpec) DeepCopy() *GatewayHealthPolicySpec {
	if in == nil {
		return nil
	}
	out := new(GatewayHealthPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is a deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetalLBConfig) DeepCopyInto(out *MetalLBConfig) {
	*out = *in
}

// DeepCopy is a deepcopy function, copying the receiver, creating a new MetalLBConfig.
func (in *MetalLBConfig) DeepCopy() *MetalLBConfig {
	if in == nil {
		return nil
	}
	out := new(MetalLBConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is a deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatewayReference) DeepCopyInto(out *GatewayReference) {
	*out = *in
}

// DeepCopy is a deepcopy function, copying the receiver, creating a new GatewayReference.
func (in *GatewayReference) DeepCopy() *GatewayReference {
	if in == nil {
		return nil
	}
	out := new(GatewayReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is a deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatewayHealthPolicyStatus) DeepCopyInto(out *GatewayHealthPolicyStatus) {
	*out = *in
	if in.Gateways != nil {
		in, out := &in.Gateways, &out.Gateways
		*out = make([]GatewayStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is a deepcopy function, copying the receiver, creating a new GatewayHealthPolicyStatus.
func (in *GatewayHealthPolicyStatus) DeepCopy() *GatewayHealthPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(GatewayHealthPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is a deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatewayStatus) DeepCopyInto(out *GatewayStatus) {
	*out = *in
	if in.IPs != nil {
		in, out := &in.IPs, &out.IPs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.LastTransitionTime != nil {
		in, out := &in.LastTransitionTime, &out.LastTransitionTime
		*out = (*in).DeepCopy()
	}
	if in.Timer != nil {
		in, out := &in.Timer, &out.Timer
		*out = new(TimerStatus)
		**out = **in
	}
}

// DeepCopy is a deepcopy function, copying the receiver, creating a new GatewayStatus.
func (in *GatewayStatus) DeepCopy() *GatewayStatus {
	if in == nil {
		return nil
	}
	out := new(GatewayStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is a deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TimerStatus) DeepCopyInto(out *TimerStatus) {
	*out = *in
}

// DeepCopy is a deepcopy function, copying the receiver, creating a new TimerStatus.
func (in *TimerStatus) DeepCopy() *TimerStatus {
	if in == nil {
		return nil
	}
	out := new(TimerStatus)
	in.DeepCopyInto(out)
	return out
}
